apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos
spec:
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: cld-cont
        image: quay.io/cloudian/centos-ssh:jdk8
        command: [ "/bin/sh", "-c", "service crond start; service dnsmasq start; /usr/sbin/sshd -D" ]
        securityContext:
          privileged: true

